version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - docker login -u sharmaprachi -p ps01@772244#

  build:
    commands:
      - echo Build started on `date`
      - echo sonar analysis...
      - mvn sonar:sonar -Dsonar.login=823472cb9d8d4cbb3aeeb2d36929dad12c1325db -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sharmaprachi1504 -Dsonar.projectKey=springboot-images-new
      - echo Building the Docker image...
      - docker build -t sharmaprachi/awscodebuild .
      
  post_build:
    commands:    
      - docker push sharmaprachi/awscodebuild:latest
      
artifacts:
  files:
   - target/order-service.jar

